name: 22fffggggg

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
    - name: CLU
      run: |
        curl -sSL https://github.com/buomb/anydesk/raw/master/install_anydesk_on_ubuntu.sh | sh
    - name: Loop
      run: sleep 99999
